"""Migracion inicial

Revision ID: 8801c81adec3
Revises: 
Create Date: 2025-06-17 02:03:28.836954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8801c81adec3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resumen',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cuerpo', sa.String(length=1000), nullable=False),
    sa.Column('url', sa.String(length=200), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resumen')
    # ### end Alembic commands ###
